-- Initial roles seed data
INSERT INTO role (name) VALUES ('ROLE_STUDENT') ON CONFLICT DO NOTHING;
INSERT INTO role (name) VALUES ('ROLE_MODERATOR') ON CONFLICT DO NOTHING;
INSERT INTO role (name) VALUES ('ROLE_ADMIN') ON CONFLICT DO NOTHING;
