spring.application.name=PlannerApi
server.port=8080
front.url=${FRONT_URL:http://localhost:4200}

spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/task_service}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update

jwt.secret=${JWT_SECRET}

file.storage.location=uploads/notes
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
