spring.application.name=PlannerApi
server.port=8080
front.url=${FRONT_URL:http://localhost:4200}

spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/task_service}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=none
spring.flyway.enabled=false
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.flyway.FlywayAutoConfiguration

jwt.secret=${JWT_SECRET}
jwt.access-token-expiration=${ACCESS_TOKEN_EXP}
jwt.refresh-token-expiration=${REFRESH_TOKEN_EXP}

file.storage.location=uploads/notes
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# AI Service Configuration
ai.service.url=${AI_SERVICE_URL:http://localhost:8000}

spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.deserialization.fail-on-unknown-properties=false

spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# AWS S3 Configuration
aws.s3.bucket-name=plannerai-notes-bucket
aws.s3.region=eu-north-1
aws.access-key=${AWS_ACCESS_KEY_ID}
aws.secret-key=${AWS_SECRET_ACCESS_KEY}
