spring.application.name=TaskApi
server.port=8080

spring.datasource.username=kdshawn
spring.datasource.password=Alim1234

spring.datasource.url=jdbc:postgresql://localhost:5432/task_service
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update

jwt.secret=dsdsadsadsadsadsadsadsadadsadsds

file.storage.location=uploads/notes
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
